export const products = [
    {
        id: 111, 
        thumbnail:"./img/tshirts/1.jpg",
        name: "Dress",
        category: "Women",
        date: "10.08.21",
        prize: 54,
        stock: 100,
    },
    {
        id: 112, 
        thumbnail:"./img/modestydress/2.jpg",
        name: "Pants",
        category: "Men",
        date: "04.25.21",
        prize: 70,
        stock: 100,
    },
    {
        id: 113, 
        thumbnail:"./img/tshirts/1.jpg",
        name: "Tshirt",
        category: "Unisex",
        date: "10.09.21",
        prize: 45,
        stock: 100,
    },
    {
        id: 114, 
        thumbnail:"./img/modestydress/2.jpg",
        name: "Dress",
        category: "Women",
        date: "07.14.21",
        prize: 80,
        stock: 100,
    },
    {
        id: 115, 
        thumbnail:"./img/tshirts/1.jpg",
        name: "Tshirt",
        category: "Unisex",
        date: "10.09.21",
        prize: 45,
        stock: 100,
    },
]